### ISSUE TITLE
How to deploy

### ISSUE THREAD

**Issue by desson2** [Mayandev/notion-avatar#2]
作者你好，我想打包成静态网页，请问该如何操作呀， 我用yarn next build && next export出现了i18n的错误，您是如何部署的呢？

**Comment by Mayandev** [comment]
> 作者你好，我想打包成静态网页，请问该如何操作呀， 我用yarn next build && next export出现了i18n的错误，您是如何部署的呢？

This project is built by Next and is recommended for deployment using [Vercel](https://vercel.com/).

1. Fork this repository
2. Register Vercel and auth GitHub
3. Choose this repo to deploy
4. When you push new commit, Vercel will automatically deploy it again.

Check out more [here](https://nextjs.org/docs/deployment)
