### ISSUE TITLE
A Face Look is Transparent

### ISSUE THREAD

**Issue by dykderrick** [Mayandev/notion-avatar#24]
As shown below, if we select this type of face (first image) and a colored background, the face will look like this (second image), which is different from other type of faces. I am not sure whether it is a bug or a feature lol.

<img src="https://user-images.githubusercontent.com/33169107/159730415-28c1bdf8-6348-4277-8814-1878b805182a.png" width="400">

<img src="https://user-images.githubusercontent.com/33169107/159730589-393db0db-1a5b-450e-9b91-62ebea990d94.png" width="400">

**Comment by Mayandev** [comment]
Fixed
