### ISSUE TITLE
Icons are not displayed

### ISSUE THREAD

**Issue by jerryc127** [Mayandev/notion-avatar#6]
图标不显示
![image](https://user-images.githubusercontent.com/16351105/140650243-cc61a6be-42bd-4aad-8f57-cab1c535a509.png)

**Comment by Mayandev** [comment]
Could you provide any console information? You can Press `F12`，screenshot for console and network panel.

**Comment by jerryc127** [comment]
发现是 跟 简悦插件 起冲突了


关了简悦
![image](https://user-images.githubusercontent.com/16351105/140697884-776750e3-da16-4154-a25b-e2165dc788d0.png)

没关简悦
![image](https://user-images.githubusercontent.com/16351105/140697910-a0724679-1595-4277-890a-31f35b152b41.png)

**Comment by Mayandev** [comment]
> 发现是 跟 简悦插件 起冲突了
> 
> 关了简悦 ![image](https://user-images.githubusercontent.com/16351105/140697884-776750e3-da16-4154-a25b-e2165dc788d0.png)
> 
> 没关简悦 ![image](https://user-images.githubusercontent.com/16351105/140697910-a0724679-1595-4277-890a-31f35b152b41.png)

All right，我先关闭这个 issue，你可以将此工具的网址加入的到「简悦」的白名单中，使其不对此工具页面生效。
